---
network:
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        - 192.168.88.120/24
      nameservers:
        addresses:
          - 8.8.8.8
      routes:
        - to: default
          via: 192.168.88.1
  version: 2