---
all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_ssh_user: osboxes
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22

  mysql:
   hosts:
    nginx:
     ansible_host: 192.168.88.120



  # children:
  #    mysql:
  #     children:
  #      hosts:
  #       nginx: 192.168.88.120
  #       apache:
  #         ansible_host: 192.168.88.121
  #    srv-nginx:
  #     children:
  #      nas:
  #       ansible_host: 192.168.88.123
  #    monitoring:
  #     children:
  #      elk:
  #       ansible_host: 192.168.88.122
