---
nginx:
  hosts: 192.168.88.120
apache:
  hosts: 192.168.88.121
nas:
  hosts: 192.168.88.123
elk:
  hosts: 192.168.88.122
debian:
  hosts: 192.168.88.124
astra:
  hosts: 192.168.88.117
mysql:
  children:
    nginx: null
    apache: null
mysql2:
  children:
    debian: null
    astra: null
    nginx: null
