---
all:
  vars:
    ansible_ssh_user: debian
    # ansible_ssh_pass: debian
    ansible_become_pass: debian
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3

nginx:
 hosts:
  192.168.88.120
apache:
 hosts:
  192.168.88.121
nas:
 hosts:
  192.168.88.123
elk:
 hosts:
  192.168.88.122
debian:
 hosts:
  192.168.88.117

mysql:
 children:
  nginx:
  apache:
