---
- name: Copy config file
  ansible.builtin.copy:
    src: my-volumes/nginx-vol/
    dest: /nginx-my-vol/
    owner: agp
    group: agp
    mode: '0444'

- name: Create a new container NGINX
  community.docker.docker_container:
    name: myngnix
    image: nginx:latest
    # restart: true
    auto_remove: true
    ports:
      - "81:80"
    state: started
    networks:
      - name: my_network
        # ipv4_address: 172.20.0.2
    volumes:
      - /nginx-my-vol:/etc/nginx/conf.d/
