---
- name: Copy config file
  ansible.builtin.copy:
    src: my-volumes/nginx-vol/
    dest: nginx-vol/
    mode: '0444'

- name: Create a new container NGINX
  community.docker.docker_container:
    name: myngnix
    image: nginx:latest
    # restart: true
    auto_remove: yes
    ports:
      - "81:80"
    state: started
    networks:
      - name: my_network
        # ipv4_address: 172.20.0.2
    volumes:
      - "{{ nginx_conf_file }}":/etc/nginx/conf.d
    # restart_policy: always