---
- name: Create a new container APACHE
  community.docker.docker_container:
    name: myapache
    image: httpd
    auto_remove: yes
    # volumes:
    #   - /volumes/apache/httpd.conf:/usr/local/apache2/conf/
    ports:
      - "8080:80"
    state: started
    networks:
      - name: my_network