---
- name: Copy config file
  ansible.builtin.copy:
    src: my-volumes/nginx-vol/myweb1.conf
    dest: /var/lib/docker/volumes/nginx-vol/_data
    mode: '0444'


# - name: Create volume
#   ansible.builtin.volume:
    